apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: ${NAMESPACE}
spec:
  type: NodePort
  selector:
    app: registry
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 32000
